import PDFDocument from 'pdfkit';
import { Response } from 'express';
import logger from '../utils/logger';

export interface LeaseData {
  tenancyId: string;
  tenantName: string;
  tenantEmail: string;
  unitNumber: string;
  assetName: string;
  assetAddress: string;
  monthlyRent: number;
  leaseStart: string;
  leaseEnd: string;
  depositAmount?: number;
}

/**
 * Generate a UK-standard lease agreement PDF and stream it to the response.
 */
export const generateLeasePdf = (data: LeaseData, res: Response): void => {
  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader(
    'Content-Disposition',
    `attachment; filename="lease_${data.tenancyId}.pdf"`
  );

  const doc = new PDFDocument({ margin: 60 });
  doc.pipe(res);

  // Title
  doc
    .font('Helvetica-Bold')
    .fontSize(20)
    .text('ASSURED SHORTHOLD TENANCY AGREEMENT', { align: 'center' });
  doc.moveDown(0.5);
  doc
    .font('Helvetica')
    .fontSize(10)
    .fillColor('#555')
    .text('PropOS Enterprise — Automated Lease Generator', { align: 'center' });
  doc.fillColor('#000').moveDown(1.5);

  // Divider
  doc.moveTo(60, doc.y).lineTo(552, doc.y).stroke();
  doc.moveDown(1);

  const field = (label: string, value: string) => {
    doc.font('Helvetica-Bold').fontSize(11).text(label + ': ', { continued: true });
    doc.font('Helvetica').fontSize(11).text(value);
    doc.moveDown(0.4);
  };

  // Parties
  doc.font('Helvetica-Bold').fontSize(13).text('1. PARTIES').moveDown(0.5);
  field('Landlord / Managing Agent', 'PropOS Enterprise Ltd');
  field('Tenant Name', data.tenantName);
  field('Tenant Email', data.tenantEmail);
  doc.moveDown(0.8);

  // Property
  doc.font('Helvetica-Bold').fontSize(13).text('2. PROPERTY').moveDown(0.5);
  field('Asset / Building', data.assetName);
  field('Address', data.assetAddress);
  field('Unit Number', data.unitNumber);
  doc.moveDown(0.8);

  // Lease Terms
  doc.font('Helvetica-Bold').fontSize(13).text('3. LEASE TERMS').moveDown(0.5);
  field('Lease Start', data.leaseStart);
  field('Lease End', data.leaseEnd);
  field('Monthly Rent', `£${data.monthlyRent.toLocaleString('en-GB')}`);
  if (data.depositAmount) {
    field('Security Deposit', `£${data.depositAmount.toLocaleString('en-GB')}`);
  }
  doc.moveDown(0.8);

  // Obligations
  doc.font('Helvetica-Bold').fontSize(13).text('4. TENANT OBLIGATIONS').moveDown(0.5);
  doc.font('Helvetica').fontSize(10).list([
    'Pay rent on the agreed date each month.',
    'Keep the property in good condition.',
    'Not sublet without written consent.',
    'Allow landlord access for inspections with 24 hours notice.',
    'Adhere to UK Housing Act 1988 and applicable legislation.',
  ]);
  doc.moveDown(0.8);

  // Signatures
  doc.font('Helvetica-Bold').fontSize(13).text('5. SIGNATURES').moveDown(1);
  doc.font('Helvetica').fontSize(11);
  doc.text('Tenant: ___________________________   Date: ______________').moveDown(0.8);
  doc.text('Landlord / Agent: _________________   Date: ______________').moveDown(1);

  // Footer
  doc.fontSize(8).fillColor('#888').text(
    `Generated by PropOS Enterprise | Ref: ${data.tenancyId} | ${new Date().toISOString()}`,
    { align: 'center' }
  );

  doc.end();
  logger.info(`[Lease] PDF generated for tenancy ${data.tenancyId}`);
};
